openapi: 3.0.0
info:
  title: This is a Merchant demo for Devoxx 2019
  description: This is a Merchant demo for Devoxx 2019
  license:
    name: Eclipse Public License - v 1.0
    url: https://www.eclipse.org/legal/epl-v10.html
  version: 1.0.0
servers:
- url: http://localhost:8080/merchant
